//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppKS
{
    using System;
    using System.Collections.Generic;
    
    public partial class ЗоныХранения
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ЗоныХранения()
        {
            this.СкладскиеЗаписи = new HashSet<СкладскиеЗаписи>();
        }
    
        public int ID_зоны { get; set; }
        public int ID_склада { get; set; }
        public string НаименованиеЗоны { get; set; }
        public string Описание { get; set; }
    
        public virtual Склады Склады { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<СкладскиеЗаписи> СкладскиеЗаписи { get; set; }
    }
}
