//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppKS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Пользователи
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Пользователи()
        {
            this.ЛогиПользователей = new HashSet<ЛогиПользователей>();
            this.Отчеты = new HashSet<Отчеты>();
            this.Файлы = new HashSet<Файлы>();
            this.Штрихкоды = new HashSet<Штрихкоды>();
        }
    
        public int ID_пользователя { get; set; }
        public string ИмяПользователя { get; set; }
        public string ХэшПароля { get; set; }
        public string ЭлектроннаяПочта { get; set; }
        public string Телефон { get; set; }
        public string ПолноеИмя { get; set; }
        public int ID_роли { get; set; }
        public string СекретДвухфакторнойАутентификации { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ЛогиПользователей> ЛогиПользователей { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Отчеты> Отчеты { get; set; }
        public virtual Роли Роли { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Файлы> Файлы { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Штрихкоды> Штрихкоды { get; set; }
    }
}
