//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppKS
{
    using System;
    using System.Collections.Generic;
    
    public partial class РезультатыИнвентаризации
    {
        public int ID_результата { get; set; }
        public int ID_инвентаризации { get; set; }
        public int ID_товара { get; set; }
        public int ФактическоеКоличество { get; set; }
        public int ЗаписанноеКоличество { get; set; }
        public int Разница { get; set; }
    
        public virtual Инвентаризация Инвентаризация { get; set; }
        public virtual Товары Товары { get; set; }
    }
}
