//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppKS
{
    using System;
    using System.Collections.Generic;
    
    public partial class СкладскиеЗаписи
    {
        public int ID_записи { get; set; }
        public int ID_товара { get; set; }
        public int ID_склада { get; set; }
        public Nullable<int> ID_зоны { get; set; }
        public int Количество { get; set; }
    
        public virtual ЗоныХранения ЗоныХранения { get; set; }
        public virtual Склады Склады { get; set; }
        public virtual Товары Товары { get; set; }
    }
}
