//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppKS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Товары
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Товары()
        {
            this.ПозицииПриходнойНакладной = new HashSet<ПозицииПриходнойНакладной>();
            this.ПозицииРасходнойНакладной = new HashSet<ПозицииРасходнойНакладной>();
            this.РезультатыИнвентаризации = new HashSet<РезультатыИнвентаризации>();
            this.СкладскиеЗаписи = new HashSet<СкладскиеЗаписи>();
            this.Штрихкоды = new HashSet<Штрихкоды>();
        }
    
        public int ID_товара { get; set; }
        public string Наименование { get; set; }
        public string Артикул { get; set; }
        public string Штрихкод { get; set; }
        public string Категория { get; set; }
        public string ЕдиницаИзмерения { get; set; }
        public decimal Цена { get; set; }
        public Nullable<System.DateTime> СрокГодности { get; set; }
        public string СерийныйНомер { get; set; }
        public Nullable<int> МинимальныйОстаток { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ПозицииПриходнойНакладной> ПозицииПриходнойНакладной { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ПозицииРасходнойНакладной> ПозицииРасходнойНакладной { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<РезультатыИнвентаризации> РезультатыИнвентаризации { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<СкладскиеЗаписи> СкладскиеЗаписи { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Штрихкоды> Штрихкоды { get; set; }
    }
}
