//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppKS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Штрихкоды
    {
        public int ID_штрихкода { get; set; }
        public int ID_товара { get; set; }
        public string ДанныеШтрихкода { get; set; }
        public int СгенерированПользователем { get; set; }
        public System.DateTime ДатаГенерации { get; set; }
    
        public virtual Пользователи Пользователи { get; set; }
        public virtual Товары Товары { get; set; }
    }
}
