//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryKSS
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class СкладEntities : DbContext
    {
        public СкладEntities()
            : base("name=СкладEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<ЗоныХранения> ЗоныХранения { get; set; }
        public virtual DbSet<Инвентаризация> Инвентаризация { get; set; }
        public virtual DbSet<Клиенты> Клиенты { get; set; }
        public virtual DbSet<ЛогиПользователей> ЛогиПользователей { get; set; }
        public virtual DbSet<Отчеты> Отчеты { get; set; }
        public virtual DbSet<ПозицииПриходнойНакладной> ПозицииПриходнойНакладной { get; set; }
        public virtual DbSet<ПозицииРасходнойНакладной> ПозицииРасходнойНакладной { get; set; }
        public virtual DbSet<Пользователи> Пользователи { get; set; }
        public virtual DbSet<Поставщики> Поставщики { get; set; }
        public virtual DbSet<ПриходныеНакладные> ПриходныеНакладные { get; set; }
        public virtual DbSet<РасходныеНакладные> РасходныеНакладные { get; set; }
        public virtual DbSet<РезультатыИнвентаризации> РезультатыИнвентаризации { get; set; }
        public virtual DbSet<Роли> Роли { get; set; }
        public virtual DbSet<СкладскиеЗаписи> СкладскиеЗаписи { get; set; }
        public virtual DbSet<Склады> Склады { get; set; }
        public virtual DbSet<Товары> Товары { get; set; }
        public virtual DbSet<Файлы> Файлы { get; set; }
        public virtual DbSet<Штрихкоды> Штрихкоды { get; set; }
    }
}
