//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryKSS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Отчеты
    {
        public int ID_отчета { get; set; }
        public string ТипОтчета { get; set; }
        public int СгенерированПользователем { get; set; }
        public System.DateTime ДатаГенерации { get; set; }
        public string ДанныеОтчета { get; set; }
    
        public virtual Пользователи Пользователи { get; set; }
    }
}
