//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryKSS
{
    using System;
    using System.Collections.Generic;
    
    public partial class ПозицииРасходнойНакладной
    {
        public int ID_позиции { get; set; }
        public int ID_накладной { get; set; }
        public int ID_товара { get; set; }
        public int Количество { get; set; }
        public decimal Цена { get; set; }
    
        public virtual РасходныеНакладные РасходныеНакладные { get; set; }
        public virtual Товары Товары { get; set; }
    }
}
