//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryKSS
{
    using System;
    using System.Collections.Generic;
    
    public partial class ПриходныеНакладные
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ПриходныеНакладные()
        {
            this.ПозицииПриходнойНакладной = new HashSet<ПозицииПриходнойНакладной>();
        }
    
        public int ID_накладной { get; set; }
        public string НомерНакладной { get; set; }
        public System.DateTime ДатаПоступления { get; set; }
        public int ID_поставщика { get; set; }
        public decimal ОбщаяСумма { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ПозицииПриходнойНакладной> ПозицииПриходнойНакладной { get; set; }
        public virtual Поставщики Поставщики { get; set; }
    }
}
