//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryKSS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Файлы
    {
        public int ID_файла { get; set; }
        public string ИмяФайла { get; set; }
        public string ТипФайла { get; set; }
        public byte[] ДанныеФайла { get; set; }
        public System.DateTime ДатаЗагрузки { get; set; }
        public int ЗагруженПользователем { get; set; }
    
        public virtual Пользователи Пользователи { get; set; }
    }
}
