//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AvtoSklad
{
    using System;
    using System.Collections.Generic;
    
    public partial class Заказ
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Заказ()
        {
            this.РезервТовара = new HashSet<РезервТовара>();
            this.ЭлементЗаказа = new HashSet<ЭлементЗаказа>();
        }
    
        public int id_заказа { get; set; }
        public string тип_заказа { get; set; }
        public System.DateTime дата_заказа { get; set; }
        public Nullable<int> id_поставщика { get; set; }
        public Nullable<int> id_клиента { get; set; }
        public string статус_заказа { get; set; }
        public decimal общая_сумма { get; set; }
    
        public virtual Клиент Клиент { get; set; }
        public virtual Поставщик Поставщик { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<РезервТовара> РезервТовара { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ЭлементЗаказа> ЭлементЗаказа { get; set; }
    }
}
