//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AvtoSklad
{
    using System;
    using System.Collections.Generic;
    
    public partial class Инвентаризация
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Инвентаризация()
        {
            this.ЭлементИнвентаризации = new HashSet<ЭлементИнвентаризации>();
        }
    
        public int id_инвентаризации { get; set; }
        public System.DateTime дата_инвентаризации { get; set; }
        public string ответственное_лицо { get; set; }
        public string результаты { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ЭлементИнвентаризации> ЭлементИнвентаризации { get; set; }
    }
}
