//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AvtoSklad
{
    using System;
    using System.Collections.Generic;
    
    public partial class Пользователь
    {
        public int id_пользователя { get; set; }
        public string имя_пользователя { get; set; }
        public string email { get; set; }
        public string хэш_пароля { get; set; }
        public string роль { get; set; }
        public byte[] фото { get; set; }
        public string two_factor_token { get; set; }
    }
}
