//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AvtoSklad
{
    using System;
    using System.Collections.Generic;
    
    public partial class ПриходнаяНакладная
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ПриходнаяНакладная()
        {
            this.ЭлементПриходнойНакладной = new HashSet<ЭлементПриходнойНакладной>();
        }
    
        public int id_накладной { get; set; }
        public string номер_накладной { get; set; }
        public System.DateTime дата_поступления { get; set; }
        public int id_поставщика { get; set; }
        public decimal общая_сумма { get; set; }
    
        public virtual Поставщик Поставщик { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ЭлементПриходнойНакладной> ЭлементПриходнойНакладной { get; set; }
    }
}
