//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AvtoSklad
{
    using System;
    using System.Collections.Generic;
    
    public partial class РезервТовара
    {
        public int id_резерва { get; set; }
        public int id_заказа { get; set; }
        public int id_товара { get; set; }
        public int количество_резерва { get; set; }
        public System.DateTime дата_резерва { get; set; }
    
        public virtual Заказ Заказ { get; set; }
        public virtual Товар Товар { get; set; }
    }
}
