//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AvtoSklad
{
    using System;
    using System.Collections.Generic;
    
    public partial class Товар
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Товар()
        {
            this.РезервТовара = new HashSet<РезервТовара>();
            this.ЭлементЗаказа = new HashSet<ЭлементЗаказа>();
            this.ЭлементИнвентаризации = new HashSet<ЭлементИнвентаризации>();
            this.ЭлементПриходнойНакладной = new HashSet<ЭлементПриходнойНакладной>();
            this.ЭлементРасходнойНакладной = new HashSet<ЭлементРасходнойНакладной>();
        }
    
        public int id_товара { get; set; }
        public string название { get; set; }
        public string артикул { get; set; }
        public string штрихкод { get; set; }
        public string категория { get; set; }
        public string единица_измерения { get; set; }
        public decimal цена { get; set; }
        public string серийный_номер { get; set; }
        public Nullable<int> минимальный_запас { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<РезервТовара> РезервТовара { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ЭлементЗаказа> ЭлементЗаказа { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ЭлементИнвентаризации> ЭлементИнвентаризации { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ЭлементПриходнойНакладной> ЭлементПриходнойНакладной { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ЭлементРасходнойНакладной> ЭлементРасходнойНакладной { get; set; }
    }
}
