//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AvtoSklad
{
    using System;
    using System.Collections.Generic;
    
    public partial class ЭлементРасходнойНакладной
    {
        public int id_элемента_накладной { get; set; }
        public int id_накладной { get; set; }
        public int id_товара { get; set; }
        public int количество { get; set; }
        public decimal цена { get; set; }
    
        public virtual РасходнаяНакладная РасходнаяНакладная { get; set; }
        public virtual Товар Товар { get; set; }
    }
}
